### ISSUE TITLE
[Question/Suggestion] Adding a font

### ISSUE THREAD

**Issue by xllifi** [GabrielDja/GUI-SimpleStylized#10]
![изображение](https://github.com/GabrielDja/GUI-SimpleStylized/assets/70767436/063abddb-8e3e-4b45-bc1d-70a756f3895f)
This is what I managed to draw, would you like to add this font?

**Comment by GabrielDja** [comment]
I hadn't thought of modifying the fonts for the pack, and frankly, it looks great.

You can send me the fonts, they'll be added in the next Update.

**Thanks for your contribution :D**

**Comment by xllifi** [comment]
It indeed does look great until you start to use it. Some might like it, but I expect most to hate it. I'm going to publish it on modrinth as a standalone resourcepack. Another downside is that when it's using bold modifier y and g for example are indistinguishable.

**Comment by GabrielDja** [comment]
If not, can I define it as an Addon for this Resource Pack? **If you agree, the Addon will be available here**: 
https://gabrieldjalayer.wixsite.com/gabrieldja-gaming-yt/gui-simplestylized#addons

**By crediting you, of course!**

**Comment by xllifi** [comment]
Yeah, sure
By the way, website didnt switch to english for me. Probably because my default language is Russian, and when the site doesn't find it, it falls back to default (French). So consider making English the default language, please

**Comment by GabrielDja** [comment]
Yes, the site is by default in French.
We will try to make a system so that its detects the language of users on the site

Thank you for letting me know!
