### ISSUE TITLE
incorrect credits

### ISSUE THREAD

**Issue by xllifi** [GabrielDja/GUI-SimpleStylized#15]
<img src="https://github.com/GabrielDja/GUI-SimpleStylized/assets/70767436/8d04036c-c885-47d5-a137-87ce6be9c4f4" width=320px></img>
I'm x**ll**ifi (2 l's)
Add a link to [my resourcepack on modrinth](https://modrinth.com/resourcepack/mc10) instead of mediafire

**Comment by GabrielDja** [comment]
Okay, I'll make the changes today :D
