### ISSUE TITLE
[Mod Support] Add ArmorPoints++ Compat

### ISSUE THREAD

**Issue by noawx** [GabrielDja/GUI-SimpleStylized#19]
Would be cool if you could add support for [Armor Points ++](https://modrinth.com/mod/armorpoints), thanks

**Comment by GabrielDja** [comment]
I looked and didn't see any Interface.
GUI SimpleStylized aims to Improve Interfaces, not just Icons.
**If you can find Mods with Interfaces, I'm interested! :D**
