### ISSUE TITLE
Add support to the following mods

### ISSUE THREAD

**Issue by MbtMarco** [GabrielDja/GUI-SimpleStylized#21]
https://modrinth.com/mod/advancement-plaques

https://modrinth.com/mod/emi

**Comment by GabrielDja** [comment]
Thank you for your suggestions,
**EMI** is already taken care of in the pack.
And **Advancement Plaques** will be available for the next version :D

**EMI Textures not working on your end?**

**Comment by MbtMarco** [comment]
To be honest I had not tried Emi yet, I asked because I hadn't seen it in the list of supported mods. 😂

**Comment by GabrielDja** [comment]
It's okay, I don't blame you 😁
