### ISSUE TITLE
JEI compatibility not working

### ISSUE THREAD

**Issue by Spazer-Prime** [GabrielDja/GUI-SimpleStylized#22]
I also tried disabling all other mods and resourcepacks besides JEI and GUI Simple Stylized, just to be sure, and it still doesn't seem to work. 
Minecraft: 1.20.1
JEI: 15.2.0.27
GUI-SS: 3.7-1.20+
![2023-10-20_21 56 18](https://github.com/GabrielDja/GUI-SimpleStylized/assets/146499778/50ab3944-0534-45a9-b5a5-a7f2f7ff94aa)

**Comment by GabrielDja** [comment]
I just fixed the problem and it will work in **GUI SimpleStylized v3.8** :D
