### ISSUE TITLE
[bug] [1.20.2] Traveler's Backpack Incompability

### ISSUE THREAD

**Issue by noawx** [GabrielDja/GUI-SimpleStylized#23]
The Traveler's Backpack mod had their tool slot system revamped in the update 9.2.0

The texture pack isn't able to account for the revamp, and thus some parts of the backpack GUI are invisible or broken.

**Comment by GabrielDja** [comment]
I just fixed the problem and it will work in **GUI SimpleStylized v3.8** :D
