### ISSUE TITLE
[bug] Challenge Advancement Frames look weird

### ISSUE THREAD

**Issue by noawx** [GabrielDja/GUI-SimpleStylized#24]
![image](https://github.com/GabrielDja/GUI-SimpleStylized/assets/76262280/992b68fe-fbcc-467c-9748-1745a11988fa)
They look like this, off-center and stretched.

[List of Mods Installed](https://hst.sh/ligakocoya.diff)

**Comment by GabrielDja** [comment]
I see a texture problem with the tabs.
I'll make some adjustments to the advancement window :D

**Comment by GabrielDja** [comment]
I just fixed the problem and it will work in **GUI SimpleStylized v3.8** :D
