### ISSUE TITLE
[Bug?] Text in trading interface missing

### ISSUE THREAD

**Issue by Spazer-Prime** [GabrielDja/GUI-SimpleStylized#26]
The "trades" and villager profession text do not appear in the trading interface, unsure if this is intentional.
Minecraft: 1.20.1
GUI-SimpleStylized_3.8-1.20+
![2023-10-29_21 07 19](https://github.com/GabrielDja/GUI-SimpleStylized/assets/146499778/d1c24982-8cc9-4730-ac5d-db0fce74717f)
![2023-10-29_21 06 53](https://github.com/GabrielDja/GUI-SimpleStylized/assets/146499778/655f7f23-81a0-4fd1-8d7d-f26e316ae7ea)

**Comment by GabrielDja** [comment]
I just fixed the problem and it will work in **GUI SimpleStylized v3.9** :D
