### ISSUE TITLE
[Request] Support for some of Fuzs's other mods

### ISSUE THREAD

**Issue by Spazer-Prime** [GabrielDja/GUI-SimpleStylized#27]
I noticed easy magic in the mod compatibility list and was wondering if support could be added for some of the author's other mods.

The nametag interface in [Easy Anvils](https://modrinth.com/mod/easy-anvils):
![2023-10-29_21 08 31](https://github.com/GabrielDja/GUI-SimpleStylized/assets/146499778/2b05301a-931f-428d-92e7-b5046641209d)

The [Bartering Station](https://modrinth.com/mod/bartering-station) interface:
![2023-10-29_21 14 33](https://github.com/GabrielDja/GUI-SimpleStylized/assets/146499778/91ab4837-011b-49c3-8f7a-46e289946ff8)

The [Stylish Effects](https://modrinth.com/mod/stylish-effects) Icons:
![2023-10-29_21 10 14](https://github.com/GabrielDja/GUI-SimpleStylized/assets/146499778/85397740-ba8d-4132-91b2-7ae03a896695)

**Comment by GabrielDja** [comment]
Mods are now supported and will be available in version **3.9**
