### ISSUE TITLE
Nemo's Woodcutter issues

### ISSUE THREAD

**Issue by nco2k** [GabrielDja/GUI-SimpleStylized#28]
im attempting to create support for [Nemo's Woodcutter](https://modrinth.com/mod/nemoswoodcutter), which seems fairly easy since it looks exactly like the Stone Cutter.

1.) i noticed that it has a [recipe_disabled.png](https://modrinth.com/resourcepack/nemos-woodcutter-dark-gui), which i cant find anywhere in GUI-SimpleStylized. how is that sprite supposed to look like?

2.) it now lacks the Wood Cutter text. why is that happening and how can i fix it?
![ezgif-3-dbcc161162](https://github.com/GabrielDja/GUI-SimpleStylized/assets/26080123/537cfb3b-ab3e-4fb1-bb1e-4c448f82b9d4)

**Comment by GabrielDja** [comment]
The "recipe_disabled.png" texture is the "recipe_selected.png" texture in vanilla.

You need to modify the "en_us" language file and add "\u00a77" to the Woodcutter value.
Example: "translation.key": "\u00a77Woodcutter"

**Comment by nco2k** [comment]
thanks for your reply, its working now. did i understand this correctly, i can use GUI-SimpleStylized's recipe_selected.png for Nemo's Woodcutter recipe_disabled.png? if thats the case, then im done: [pack.zip](https://github.com/GabrielDja/GUI-SimpleStylized/files/14764523/pack.zip)

feel free to use it however you like.

**Comment by GabrielDja** [comment]
Yes, you can use it.
However, would you like me to integrate your Nemo's Woodcutter modifications into GUI SimpleStylized?
You'll be credited like everyone else.

**Comment by nco2k** [comment]
of course. :)
