### ISSUE TITLE
Creative Inventory Arrows

### ISSUE THREAD

**Issue by nco2k** [GabrielDja/GUI-SimpleStylized#31]
i found some more issues with the creative inventory. the highlight color should be green, and the shape of the disabled arrow should match the others. i wanted to fix it myself, but i couldnt find the files. 😅

![pic](https://github.com/GabrielDja/GUI-SimpleStylized/assets/26080123/8d61b14b-d8b3-4992-9c45-331ce4fc8b5b)

**Comment by GabrielDja** [comment]
For some mods, I set the hover color to blue because I think it looks better.
The arrow is not logical, I'll fix it.
Thanks a lot! :D

**Comment by nco2k** [comment]
> For some mods, I set the hover color to blue because I think it looks better.

yea but thats what the Blue Color Addon should be for. the main Resource Pack should stay consistent. people who wanna change it, can easily do it themselves.

**Comment by GabrielDja** [comment]
Yes, but the extensions only modify the vanilla interface at the moment :V
