### ISSUE TITLE
[Suggestion] Modmenu Button Font Color

### ISSUE THREAD

**Issue by nco2k** [GabrielDja/GUI-SimpleStylized#32]
i changed the font color of the modmenu button, and it fits pretty well. might be worth integrating. :D

`assets/modmenu/lang/en_us.json`
```
{
  "modmenu.title": "\u00A79Mods"
}
```
![pic1](https://github.com/GabrielDja/GUI-SimpleStylized/assets/26080123/32391314-79c4-4732-8a5d-682c6a31b9df)
![pic2](https://github.com/GabrielDja/GUI-SimpleStylized/assets/26080123/430cb074-5c79-4248-9b23-524127e1891c)

**Comment by GabrielDja** [comment]
Very good idea, your changes will be applied in the next update :D
