### ISSUE TITLE
[ETF] Entity Texture Features & Server Country Flags

### ISSUE THREAD

**Issue by nco2k** [GabrielDja/GUI-SimpleStylized#33]
i added support for two more mods. i was too lazy to create another pull request, so here is the [files.zip](https://github.com/GabrielDja/GUI-SimpleStylized/files/15053412/files.zip) :D

the [ETF] Entity Texture Features button can be found in the Resource Packs menu, and the Server Country Flags button can be found in the Multiplayer menu.

**Comment by GabrielDja** [comment]
Thank you for your contribution,
The mod "[ETF] Entity Texture Features" is already supported, but I see that the folder name has been changed.
Your changes will be taken into account in the next update.
