### ISSUE TITLE
Tab design inconsistency

### ISSUE THREAD

**Issue by Felix14-v2** [GabrielDja/GUI-SimpleStylized#6]
According to the changelog, a new tab design was added in the latest update. However, this design is different in different places:
![image](https://user-images.githubusercontent.com/75726196/230148917-bfb3f4c6-b027-4981-bd14-a03e475b2325.png)
![image](https://user-images.githubusercontent.com/75726196/230149042-c7429cb4-0159-4eab-97be-9de680353cec.png)

And the recipe book still uses the old design:
![image](https://user-images.githubusercontent.com/75726196/230148213-5b3b4abe-05fb-4de6-910c-69b9924d28ad.png)

By the way, would you like to consider adding a license to your project? My friends liked your idea, but they want to improve it and cannot do it, since you have not chosen a license that would allow modification of your work by other people, and Modrinth displays "all rights reserved":
![image](https://user-images.githubusercontent.com/75726196/230150547-90e869f2-ebc7-48a3-9c98-5b14cff94b49.png)

**Comment by GabrielDja** [comment]
Hello Felix14-v2,
The "Recipe Book" interface will arrive in v1.6.

The license will be updated in a few days.
